version: "3.9"

services:
  app:
    container_name: email_reader
    restart: always
    build: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3434:3000"
      - "5556:5555"
    env_file:
      - path: ./.env
        required: true

    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    restart: always
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
